name: 'Hello World'
description: 'Greet someone'
inputs:
  os:
    description: 'OS to generate scar bin for'
    required: true
    default: 'macos'
# outputs:
#   random-number: 
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    # - run: echo Hello ${{ inputs.who-to-greet }}.
    #   shell: bash
    # - id: random-number-generator
    #   run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #   shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
    - name: Upload MacOS Scar bin
        uses: actions/upload-artifact@v2
        with:
          name: macos-scar
          path: dist/scarcli